import { auth } from '@/lib/auth';
import ConnectDB from '@/lib/connectionDB';
import getUserByEmail from '@/lib/helper/getUserByEmail';
import { Inter } from 'next/font/google';
import AuthUserUpdater from './componnent/AuthUserUpdater';
import './globals.css';

const inter = Inter({ subsets: ['latin'] })


export const metadata = {
  title: 'Picture TV',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {


  ConnectDB();
  let passUserData = null;

  try {

    const session = await auth();
    const sessionemail = session?.user?.email;

    //find the user
    const user = await getUserByEmail(sessionemail);


    passUserData = {
      uid: user?.uid,
      email: user?.email,
      fullname: user?.fullname,
      role: user?.role,
      isvarified: user?.isvarified,
      createdAt: user?.createdAt
    }


  } catch (error) {
    console.log("Error From Layout Page");
    console.log(error);
  }



  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthUserUpdater session={passUserData} />
        {children}
      </body>
    </html>
  )
}

























// import { auth } from '@/lib/auth';
// import ConnectDB from '@/lib/connectionDB';
// import getUserByEmail from '@/lib/helper/getUserByEmail';
// import { Inter } from 'next/font/google';
// import AuthUserUpdater from './componnent/AuthUserUpdater';
// import './globals.css';

// const inter = Inter({ subsets: ['latin'] });

// export const metadata = {
//   title: 'Picture TV',
//   description: 'Generated by create next app',
// };

// export default async function RootLayout({ children }) {
//   ConnectDB(); // Ensure DB is connected first

//   try {
//     const session = await auth();
//     const sessionEmail = session?.user?.email;

//     if (!sessionEmail) {
//       throw new Error('No email found in session');
//     }

//     // Find the user by email
//     const user = await getUserByEmail(sessionEmail);

//     const passUserData = {
//       uid: user?.uid,
//       email: user?.email,
//       fullname: user?.fullname,
//       role: user?.role,
//       isvarified: user?.isvarified,
//       createdAt: user?.createdAt,
//     };

//     return (
//       <html lang="en">
//         <body className={inter.className}>
//           <AuthUserUpdater session={passUserData} />
//           {children}
//         </body>
//       </html>
//     );
//   } catch (error) {
//     console.error('Error from getusersession', error);
//     // Optionally, render an error state if needed
//     return (
//       <html lang="en">
//         <body className={inter.className}>
//           <div>Error loading user data</div>
//           {children}
//         </body>
//       </html>
//     );
//   }
// }
