import { auth } from '@/lib/auth';
import ConnectDB from '@/lib/connectionDB';
import getUserByEmail from '@/lib/helper/getUserByEmail';
import { Inter } from 'next/font/google';
import AuthUserUpdater from './componnent/AuthUserUpdater';
import './globals.css';

const inter = Inter({ subsets: ['latin'] })


export const metadata = {
  title: 'Picture TV',
  description: 'Generated by create next app',
}



async function gertusersession() {

  try {

    const session = await auth();
    const sessionemail = session?.user?.email;

    //find the user
    const user = await getUserByEmail(sessionemail);


    const passUserData = {
      uid: user?.uid,
      email: user?.email,
      fullname: user?.fullname,
      role: user?.role,
      isvarified: user?.isvarified,
      createdAt: user?.createdAt
    }

    return passUserData;

  } catch (error) {
    console.log("Error from getusersession");
    console.log(error);
  }

}







export default async function RootLayout({ children }) {


  const authUser = await gertusersession();

  ConnectDB();

  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthUserUpdater session={authUser} />
        {children}
      </body>
    </html>
  )
}
