import ConnectDB from '@/lib/connectionDB';
// import gertusersession from '@/lib/helper/getusersesssion';
import { Inter } from 'next/font/google';
// import AuthUserUpdater from './componnent/AuthUserUpdater';
import './globals.css';
const inter = Inter({ subsets: ['latin'] })


export const metadata = {
  title: 'Picture TV',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {


  // const authUser = await gertusersession();

  ConnectDB();

  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <AuthUserUpdater session={authUser} /> */}
        {children}
      </body>
    </html>
  )
}
